//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySMA.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MySMA.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string AnswerDefinition_PromptText_1 {
            get {
                return ResourceManager.GetString("AnswerDefinition_PromptText_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string AnswerDefinition_PromptText_10 {
            get {
                return ResourceManager.GetString("AnswerDefinition_PromptText_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        public static string AnswerDefinition_PromptText_13 {
            get {
                return ResourceManager.GetString("AnswerDefinition_PromptText_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        public static string AnswerDefinition_PromptText_14 {
            get {
                return ResourceManager.GetString("AnswerDefinition_PromptText_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        public static string AnswerDefinition_PromptText_15 {
            get {
                return ResourceManager.GetString("AnswerDefinition_PromptText_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        public static string AnswerDefinition_PromptText_16 {
            get {
                return ResourceManager.GetString("AnswerDefinition_PromptText_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17.
        /// </summary>
        public static string AnswerDefinition_PromptText_17 {
            get {
                return ResourceManager.GetString("AnswerDefinition_PromptText_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18.
        /// </summary>
        public static string AnswerDefinition_PromptText_18 {
            get {
                return ResourceManager.GetString("AnswerDefinition_PromptText_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19.
        /// </summary>
        public static string AnswerDefinition_PromptText_19 {
            get {
                return ResourceManager.GetString("AnswerDefinition_PromptText_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string AnswerDefinition_PromptText_2 {
            get {
                return ResourceManager.GetString("AnswerDefinition_PromptText_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        public static string AnswerDefinition_PromptText_20 {
            get {
                return ResourceManager.GetString("AnswerDefinition_PromptText_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string AnswerDefinition_PromptText_3 {
            get {
                return ResourceManager.GetString("AnswerDefinition_PromptText_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string AnswerDefinition_PromptText_4 {
            get {
                return ResourceManager.GetString("AnswerDefinition_PromptText_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string AnswerDefinition_PromptText_5 {
            get {
                return ResourceManager.GetString("AnswerDefinition_PromptText_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string AnswerDefinition_PromptText_6 {
            get {
                return ResourceManager.GetString("AnswerDefinition_PromptText_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        public static string AnswerDefinition_PromptText_7 {
            get {
                return ResourceManager.GetString("AnswerDefinition_PromptText_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        public static string AnswerDefinition_PromptText_8 {
            get {
                return ResourceManager.GetString("AnswerDefinition_PromptText_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        public static string AnswerDefinition_PromptText_9 {
            get {
                return ResourceManager.GetString("AnswerDefinition_PromptText_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AnswerDefinition_PromptText_BlankOption {
            get {
                return ResourceManager.GetString("AnswerDefinition_PromptText_BlankOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporation.
        /// </summary>
        public static string AnswerDefinition_PromptText_Corporation {
            get {
                return ResourceManager.GetString("AnswerDefinition_PromptText_Corporation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater than 20.
        /// </summary>
        public static string AnswerDefinition_PromptText_GreaterThan20 {
            get {
                return ResourceManager.GetString("AnswerDefinition_PromptText_GreaterThan20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Independent Contractor/1099 Employee.
        /// </summary>
        public static string AnswerDefinition_PromptText_IndependentContractor {
            get {
                return ResourceManager.GetString("AnswerDefinition_PromptText_IndependentContractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;12.
        /// </summary>
        public static string AnswerDefinition_PromptText_LessThan12 {
            get {
                return ResourceManager.GetString("AnswerDefinition_PromptText_LessThan12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Married.
        /// </summary>
        public static string AnswerDefinition_PromptText_Married {
            get {
                return ResourceManager.GetString("AnswerDefinition_PromptText_Married", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string AnswerDefinition_PromptText_No {
            get {
                return ResourceManager.GetString("AnswerDefinition_PromptText_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partnership/LLC.
        /// </summary>
        public static string AnswerDefinition_PromptText_Partnership {
            get {
                return ResourceManager.GetString("AnswerDefinition_PromptText_Partnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule C/Sole Proprietor.
        /// </summary>
        public static string AnswerDefinition_PromptText_ScheduleC {
            get {
                return ResourceManager.GetString("AnswerDefinition_PromptText_ScheduleC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S-Corporation.
        /// </summary>
        public static string AnswerDefinition_PromptText_SCorporation {
            get {
                return ResourceManager.GetString("AnswerDefinition_PromptText_SCorporation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separated.
        /// </summary>
        public static string AnswerDefinition_PromptText_Separated {
            get {
                return ResourceManager.GetString("AnswerDefinition_PromptText_Separated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmarried.
        /// </summary>
        public static string AnswerDefinition_PromptText_UnMarried {
            get {
                return ResourceManager.GetString("AnswerDefinition_PromptText_UnMarried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string AnswerDefinition_PromptText_Yes {
            get {
                return ResourceManager.GetString("AnswerDefinition_PromptText_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  |Alabama|Alaska|Arizona|Arkansas|California|Colorado|Connecticut|Delaware|Florida|Georgia|Hawaii|Idaho|Illinois|Indiana|Iowa|Kansas|Kentucky|Louisiana|Maine|Maryland|Massachusetts|Michigan|Minnesota|Mississippi|Missouri|Montana|Nebraska|Nevada|New Hampshire|New Jersey|New Mexico|New York|North Carolina|North Dakota|Ohio|Oklahoma|Oregon|Pennsylvania|Rhode Island|South Carolina|South Dakota|Tennessee|Texas|Utah|Vermont|Virginia|Washington|West Virginia|Wisconsin|Wyoming.
        /// </summary>
        public static string PossibleAnswer_PromptText_States {
            get {
                return ResourceManager.GetString("PossibleAnswer_PromptText_States", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 year fixed.
        /// </summary>
        public static string PossibleAnswers_PromptText_10YearFixed {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_10YearFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 year fixed.
        /// </summary>
        public static string PossibleAnswers_PromptText_15YearFixed {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_15YearFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 year fixed.
        /// </summary>
        public static string PossibleAnswers_PromptText_20YearFixed {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_20YearFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25 year fixed.
        /// </summary>
        public static string PossibleAnswers_PromptText_25YearFixed {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_25YearFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 unit (duplex).
        /// </summary>
        public static string PossibleAnswers_PromptText_2Unit {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_2Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 year fixed.
        /// </summary>
        public static string PossibleAnswers_PromptText_30YearFixed {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_30YearFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 unit.
        /// </summary>
        public static string PossibleAnswers_PromptText_3Unit {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_3Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 unit.
        /// </summary>
        public static string PossibleAnswers_PromptText_4Unit {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_4Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above average 720 +.
        /// </summary>
        public static string PossibleAnswers_PromptText_AboveAverage {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_AboveAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustable rate mortgage.
        /// </summary>
        public static string PossibleAnswers_PromptText_AdjustableRateMortgage {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_AdjustableRateMortgage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string PossibleAnswers_PromptText_April {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string PossibleAnswers_PromptText_Augst {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_Augst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average 620-659.
        /// </summary>
        public static string PossibleAnswers_PromptText_Average {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below average 580-619.
        /// </summary>
        public static string PossibleAnswers_PromptText_BelowAverage {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_BelowAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        public static string PossibleAnswers_PromptText_Child {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial property.
        /// </summary>
        public static string PossibleAnswers_PromptText_CommercialProperty {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_CommercialProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condo/Townhouse/Condex.
        /// </summary>
        public static string PossibleAnswers_PromptText_CondoTownhouseCondex {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_CondoTownhouseCondex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently under contract.
        /// </summary>
        public static string PossibleAnswers_PromptText_CurrentlyUnderContract {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_CurrentlyUnderContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string PossibleAnswers_PromptText_December {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don’t know.
        /// </summary>
        public static string PossibleAnswers_PromptText_DoNotKnow {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_DoNotKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploring options.
        /// </summary>
        public static string PossibleAnswers_PromptText_ExploringOptions {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_ExploringOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string PossibleAnswers_PromptText_February {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good 660-719.
        /// </summary>
        public static string PossibleAnswers_PromptText_Good {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our home is currently under agreement.
        /// </summary>
        public static string PossibleAnswers_PromptText_HomeUnderAgreement {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_HomeUnderAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Housing/Quarters allowance.
        /// </summary>
        public static string PossibleAnswers_PromptText_HousingQuartersAllowance {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_HousingQuartersAllowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment property.
        /// </summary>
        public static string PossibleAnswers_PromptText_InvestmentProperty {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_InvestmentProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string PossibleAnswers_PromptText_January {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jointly.
        /// </summary>
        public static string PossibleAnswers_PromptText_Jointly {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_Jointly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joint Tenants.
        /// </summary>
        public static string PossibleAnswers_PromptText_JointTenants {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_JointTenants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string PossibleAnswers_PromptText_July {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string PossibleAnswers_PromptText_June {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot.
        /// </summary>
        public static string PossibleAnswers_PromptText_Lot {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_Lot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string PossibleAnswers_PromptText_March {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string PossibleAnswers_PromptText_May {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military base pay.
        /// </summary>
        public static string PossibleAnswers_PromptText_MilitaryBasePay {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_MilitaryBasePay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military Duty.
        /// </summary>
        public static string PossibleAnswers_PromptText_MilitaryDuty {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_MilitaryDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move in after 60 days.
        /// </summary>
        public static string PossibleAnswers_PromptText_MoveInAfter60Days {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_MoveInAfter60Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move into in upon closing.
        /// </summary>
        public static string PossibleAnswers_PromptText_MoveIntoInUponClosing {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_MoveIntoInUponClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move in within 60 days.
        /// </summary>
        public static string PossibleAnswers_PromptText_MoveInWithin60Days {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_MoveInWithin60Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We/I are going to move into new home then figure out what we want to do with it.
        /// </summary>
        public static string PossibleAnswers_PromptText_MoveToNewHomeThenDecideWhatToDoWithOld {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_MoveToNewHomeThenDecideWhatToDoWithOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string PossibleAnswers_PromptText_November {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string PossibleAnswers_PromptText_October {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Pending/found a house.
        /// </summary>
        public static string PossibleAnswers_PromptText_OfferPendingAHouse {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_OfferPendingAHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string PossibleAnswers_PromptText_Other {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Own.
        /// </summary>
        public static string PossibleAnswers_PromptText_Own {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_Own", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        public static string PossibleAnswers_PromptText_Parent {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan on purchasing a property in the next 2-4 months.
        /// </summary>
        public static string PossibleAnswers_PromptText_PlanOnPurchasingAProperty {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_PlanOnPurchasingAProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We/I plan to put it on the market soon.
        /// </summary>
        public static string PossibleAnswers_PromptText_PlanToPutToMarket {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_PlanToPutToMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary residence.
        /// </summary>
        public static string PossibleAnswers_PromptText_PrimaryResidence {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_PrimaryResidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative.
        /// </summary>
        public static string PossibleAnswers_PromptText_Relative {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_Relative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent.
        /// </summary>
        public static string PossibleAnswers_PromptText_Rent {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_Rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We/I plan to rent current home and move into new home.
        /// </summary>
        public static string PossibleAnswers_PromptText_RentCurrentAndMoveToNewHome {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_RentCurrentAndMoveToNewHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve income.
        /// </summary>
        public static string PossibleAnswers_PromptText_ReserveIncome {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_ReserveIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserves/National Guard.
        /// </summary>
        public static string PossibleAnswers_PromptText_ReservesNationalGuard {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_ReservesNationalGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second home.
        /// </summary>
        public static string PossibleAnswers_PromptText_SecondHome {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_SecondHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving and selling current home at or about the same time.
        /// </summary>
        public static string PossibleAnswers_PromptText_SellingCurrentHomeSameTime {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_SellingCurrentHomeSameTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string PossibleAnswers_PromptText_September {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sibling.
        /// </summary>
        public static string PossibleAnswers_PromptText_Sibling {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_Sibling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string PossibleAnswers_PromptText_Single {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single family.
        /// </summary>
        public static string PossibleAnswers_PromptText_SingleFamily {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_SingleFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Man.
        /// </summary>
        public static string PossibleAnswers_PromptText_SingleMan {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_SingleMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Woman.
        /// </summary>
        public static string PossibleAnswers_PromptText_SingleWoman {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_SingleWoman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trust.
        /// </summary>
        public static string PossibleAnswers_PromptText_Trust {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_Trust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string PossibleAnswers_PromptText_Unknown {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use it as a vacation (second) home.
        /// </summary>
        public static string PossibleAnswers_PromptText_UseItAsVacationHome {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_UseItAsVacationHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This purchase will be an investment/rental property.
        /// </summary>
        public static string PossibleAnswers_PromptText_WillBeAnInvestmentProperty {
            get {
                return ResourceManager.GetString("PossibleAnswers_PromptText_WillBeAnInvestmentProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Question_DisplayName_Address {
            get {
                return ResourceManager.GetString("Question_DisplayName_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount owed.
        /// </summary>
        public static string Question_DisplayName_AmountOwed {
            get {
                return ResourceManager.GetString("Question_DisplayName_AmountOwed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Question_DisplayName_City {
            get {
                return ResourceManager.GetString("Question_DisplayName_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string Question_DisplayName_ContactName {
            get {
                return ResourceManager.GetString("Question_DisplayName_ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debtor name.
        /// </summary>
        public static string Question_DisplayName_Debtor {
            get {
                return ResourceManager.GetString("Question_DisplayName_Debtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Question_DisplayName_EmailAddress {
            get {
                return ResourceManager.GetString("Question_DisplayName_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer Name.
        /// </summary>
        public static string Question_DisplayName_EmployerName {
            get {
                return ResourceManager.GetString("Question_DisplayName_EmployerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Question_DisplayName_Month {
            get {
                return ResourceManager.GetString("Question_DisplayName_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly payment.
        /// </summary>
        public static string Question_DisplayName_MonthlyPayment {
            get {
                return ResourceManager.GetString("Question_DisplayName_MonthlyPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string Question_DisplayName_PhoneNumber {
            get {
                return ResourceManager.GetString("Question_DisplayName_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Title.
        /// </summary>
        public static string Question_DisplayName_PositionTitle {
            get {
                return ResourceManager.GetString("Question_DisplayName_PositionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Month.
        /// </summary>
        public static string Question_DisplayName_StartMonth {
            get {
                return ResourceManager.GetString("Question_DisplayName_StartMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Year.
        /// </summary>
        public static string Question_DisplayName_StartYear {
            get {
                return ResourceManager.GetString("Question_DisplayName_StartYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string Question_DisplayName_State {
            get {
                return ResourceManager.GetString("Question_DisplayName_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Question_DisplayName_Street {
            get {
                return ResourceManager.GetString("Question_DisplayName_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Question_DisplayName_Year {
            get {
                return ResourceManager.GetString("Question_DisplayName_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip code.
        /// </summary>
        public static string Question_DisplayName_Zip {
            get {
                return ResourceManager.GetString("Question_DisplayName_Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address of property.
        /// </summary>
        public static string QuestionDefinition_PromptText_AddressOfProperty {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_AddressOfProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What was the address of the property that was sold?.
        /// </summary>
        public static string QuestionDefinition_PromptText_AddressOfTheSoldProperty {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_AddressOfTheSoldProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide your agent&apos;s contact information.
        /// </summary>
        public static string QuestionDefinition_PromptText_AgentInfo {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_AgentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you receive alimony?.
        /// </summary>
        public static string QuestionDefinition_PromptText_Alimony {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_Alimony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you obligated to pay alimony?.
        /// </summary>
        public static string QuestionDefinition_PromptText_AlimonyObligation {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_AlimonyObligation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of Gift?.
        /// </summary>
        public static string QuestionDefinition_PromptText_AmountOfGift {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_AmountOfGift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much is your current monthly rent?.
        /// </summary>
        public static string QuestionDefinition_PromptText_AmountOfRent {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_AmountOfRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you provide authorization for us to pull your credit report?.
        /// </summary>
        public static string QuestionDefinition_PromptText_AuthorizeCreditReport {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_AuthorizeCreditReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type your name here.
        /// </summary>
        public static string QuestionDefinition_PromptText_AuthorizeCreditReportName {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_AuthorizeCreditReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you owe any back taxes from any previous years?.
        /// </summary>
        public static string QuestionDefinition_PromptText_BackTaxesFromAnyPreviousYears {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_BackTaxesFromAnyPreviousYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the borrower&apos;s age.
        /// </summary>
        public static string QuestionDefinition_PromptText_BorrowerAge {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_BorrowerAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the borrower&apos;s date of birth.
        /// </summary>
        public static string QuestionDefinition_PromptText_BorrowerDateOfBirth {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_BorrowerDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has the business filed an extension for this past year&apos;s tax return?.
        /// </summary>
        public static string QuestionDefinition_PromptText_BusinessTaxExtension {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_BusinessTaxExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the borrower&apos;s child&apos;s age.
        /// </summary>
        public static string QuestionDefinition_PromptText_ChildAge {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_ChildAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you required to pay child support?.
        /// </summary>
        public static string QuestionDefinition_PromptText_ChildSupport {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_ChildSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the closing date of your current home?.
        /// </summary>
        public static string QuestionDefinition_PromptText_ClosingDate {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_ClosingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you a co-maker or endorser on a note?.
        /// </summary>
        public static string QuestionDefinition_PromptText_CoMakerOrEndorser {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_CoMakerOrEndorser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How would you rate your credit?.
        /// </summary>
        public static string QuestionDefinition_PromptText_CreditRating {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_CreditRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your current address?.
        /// </summary>
        public static string QuestionDefinition_PromptText_CurrentAddress {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_CurrentAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your plan with your current home?.
        /// </summary>
        public static string QuestionDefinition_PromptText_CurrentHomePlan {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_CurrentHomePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your current household income?.
        /// </summary>
        public static string QuestionDefinition_PromptText_CurrentHouseholdIncome {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_CurrentHouseholdIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who is the current lien holder?.
        /// </summary>
        public static string QuestionDefinition_PromptText_CurrentLienHolder {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_CurrentLienHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you currently party to a lawsuit?.
        /// </summary>
        public static string QuestionDefinition_PromptText_CurrentlyPartyToALawsuit {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_CurrentlyPartyToALawsuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you currently working with a real estate agent?.
        /// </summary>
        public static string QuestionDefinition_PromptText_CurrentRealEstateAgent {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_CurrentRealEstateAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When was the property foreclosed on?.
        /// </summary>
        public static string QuestionDefinition_PromptText_DateOfPropertyForeclosed {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_DateOfPropertyForeclosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When did you purchase the property?.
        /// </summary>
        public static string QuestionDefinition_PromptText_DateOfPropertyPurchase {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_DateOfPropertyPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What was the date of sale?.
        /// </summary>
        public static string QuestionDefinition_PromptText_DateOfSale {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_DateOfSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When did the short sale occur?.
        /// </summary>
        public static string QuestionDefinition_PromptText_DateOfShortSale {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_DateOfShortSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you been declared bankrupt in the past 7 years?.
        /// </summary>
        public static string QuestionDefinition_PromptText_DeclaredBankrupt {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_DeclaredBankrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have any dependents?.
        /// </summary>
        public static string QuestionDefinition_PromptText_DependencyExistance {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_DependencyExistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is any part of your down payment borrowed?.
        /// </summary>
        public static string QuestionDefinition_PromptText_DownPaymentBorrowed {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_DownPaymentBorrowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will any part of your downpayment come from your checking or savings account?.
        /// </summary>
        public static string QuestionDefinition_PromptText_DownpaymentCheckingOrSavingsAccount {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_DownpaymentCheckingOrSavingsAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will any part of your downpayment come from equity from pending sale?.
        /// </summary>
        public static string QuestionDefinition_PromptText_DownpaymentEquityFromPendingSale {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_DownpaymentEquityFromPendingSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will any part of your downpayment come from a gift?.
        /// </summary>
        public static string QuestionDefinition_PromptText_DownpaymentGift {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_DownpaymentGift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will any part of your downpayment come from your Retirement or 401K loan or withdrawal?.
        /// </summary>
        public static string QuestionDefinition_PromptText_DownpaymentRetirement401KLoanOrWithdrawal {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_DownpaymentRetirement401KLoanOrWithdrawal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will any part of your downpayment come from Sale of Stock or Bonds?.
        /// </summary>
        public static string QuestionDefinition_PromptText_DownpaymentSaleOfStockOrBonds {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_DownpaymentSaleOfStockOrBonds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long have you lived there?.
        /// </summary>
        public static string QuestionDefinition_PromptText_DurationAtCurrentRental {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_DurationAtCurrentRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long did you live at this address?.
        /// </summary>
        public static string QuestionDefinition_PromptText_DurationAtPreviousAddress {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_DurationAtPreviousAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long did you live at this address?.
        /// </summary>
        public static string QuestionDefinition_PromptText_DurationAtPreviousRental {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_DurationAtPreviousRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many years have you been in your current profession?.
        /// </summary>
        public static string QuestionDefinition_PromptText_DurationInCurrentProfession {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_DurationInCurrentProfession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long is alimony expected to continue?.
        /// </summary>
        public static string QuestionDefinition_PromptText_DurationOfAlimony {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_DurationOfAlimony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long are you expected to pay alimony?.
        /// </summary>
        public static string QuestionDefinition_PromptText_DurationOfAlimonyObligation {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_DurationOfAlimonyObligation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long is child support expected to continue?.
        /// </summary>
        public static string QuestionDefinition_PromptText_DurationOfChildSupport {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_DurationOfChildSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long are you obligated to pay?.
        /// </summary>
        public static string QuestionDefinition_PromptText_DurationOfChildSupportObligation {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_DurationOfChildSupportObligation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long have you been self-employed?.
        /// </summary>
        public static string QuestionDefinition_PromptText_DurationOfSelfEmployement {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_DurationOfSelfEmployement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide your employer&apos;s contact information.
        /// </summary>
        public static string QuestionDefinition_PromptText_EmployerInfo {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_EmployerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you have any gaps in employment over the past 2 years greater than 30 days?.
        /// </summary>
        public static string QuestionDefinition_PromptText_EmploymentGaps {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_EmploymentGaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to escrow hazard (homeowners) insurance in the loan?.
        /// </summary>
        public static string QuestionDefinition_PromptText_EscrowHazardInsuranceInLoan {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_EscrowHazardInsuranceInLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to escrow taxes in the loan?.
        /// </summary>
        public static string QuestionDefinition_PromptText_EscrowTaxesInTheLoan {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_EscrowTaxesInTheLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your estimated purchase price?.
        /// </summary>
        public static string QuestionDefinition_PromptText_EstimatedPurchasePrice {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_EstimatedPurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have experience owning investment properties?.
        /// </summary>
        public static string QuestionDefinition_PromptText_ExperienceOfInvestmentProperties {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_ExperienceOfInvestmentProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you file a tax extension for the most recent year?.
        /// </summary>
        public static string QuestionDefinition_PromptText_FileATaxExtension {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_FileATaxExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you graduate from college in the past 2 years?.
        /// </summary>
        public static string QuestionDefinition_PromptText_GraduateFromCollege {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_GraduateFromCollege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How did you hold the title?.
        /// </summary>
        public static string QuestionDefinition_PromptText_HoldTitle {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_HoldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your intention for the new property?.
        /// </summary>
        public static string QuestionDefinition_PromptText_IntentionForTheNewProperty {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_IntentionForTheNewProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you listed as permanently disabled?.
        /// </summary>
        public static string QuestionDefinition_PromptText_ListedAsPermanentlyDisabled {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_ListedAsPermanentlyDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your marital status?.
        /// </summary>
        public static string QuestionDefinition_PromptText_MaritalStatus {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you receive any of these military benefits?.
        /// </summary>
        public static string QuestionDefinition_PromptText_MilitaryBenefits {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_MilitaryBenefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which branch of the military?.
        /// </summary>
        public static string QuestionDefinition_PromptText_MilitaryBranch {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_MilitaryBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter number of dependents.
        /// </summary>
        public static string QuestionDefinition_PromptText_NumberOfChildDependents {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_NumberOfChildDependents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many dependents do you have?.
        /// </summary>
        public static string QuestionDefinition_PromptText_NumberOfDependents {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_NumberOfDependents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you been obligated on any loan resulted in foreclosure, transfer of title in lieu of foreclosure, or judgement?.
        /// </summary>
        public static string QuestionDefinition_PromptText_ObligatedOnAnyLoan {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_ObligatedOnAnyLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you pay more than one parent?.
        /// </summary>
        public static string QuestionDefinition_PromptText_OneOrMoreParentChildSupport {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_OneOrMoreParentChildSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you also have any other business interests?.
        /// </summary>
        public static string QuestionDefinition_PromptText_OtherBusinessInterests {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_OtherBusinessInterests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are there any other sources for your downpayment that we didn&apos;t ask you about?.
        /// </summary>
        public static string QuestionDefinition_PromptText_OtherSourcesForDownpayment {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_OtherSourcesForDownpayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have any other W-2 jobs?.
        /// </summary>
        public static string QuestionDefinition_PromptText_OtherW2Jobs {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_OtherW2Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outstanding Judgements?.
        /// </summary>
        public static string QuestionDefinition_PromptText_OutstandingJudgements {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_OutstandingJudgements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have any overdraft fees on any of your bank statements?.
        /// </summary>
        public static string QuestionDefinition_PromptText_OverdraftFeesOnBankStatements {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_OverdraftFeesOnBankStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you had ownership interest in a property in the past 3 years?.
        /// </summary>
        public static string QuestionDefinition_PromptText_OwnershipInterestInAProperty {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_OwnershipInterestInAProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your total monthly payment including taxes, insurance and HOA fees (if applicable)?.
        /// </summary>
        public static string QuestionDefinition_PromptText_OwnMonthlyPayment {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_OwnMonthlyPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you own more than 25% of the partnership?.
        /// </summary>
        public static string QuestionDefinition_PromptText_OwnMoreThan25Percent {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_OwnMoreThan25Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you own or rent?.
        /// </summary>
        public static string QuestionDefinition_PromptText_OwnOrRent {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_OwnOrRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you own any properties or land?.
        /// </summary>
        public static string QuestionDefinition_PromptText_OwnPropertiesOrLand {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_OwnPropertiesOrLand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you a party to a lawsuit?.
        /// </summary>
        public static string QuestionDefinition_PromptText_PartyToALawsuit {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_PartyToALawsuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you on a payment plan?.
        /// </summary>
        public static string QuestionDefinition_PromptText_PaymentPlan {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_PaymentPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you 10% or more disabled?.
        /// </summary>
        public static string QuestionDefinition_PromptText_PercentDisabled {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_PercentDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What percent of the business do you own?.
        /// </summary>
        public static string QuestionDefinition_PromptText_PercentOfBusinessOwnership {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_PercentOfBusinessOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you a Permanent Resident?.
        /// </summary>
        public static string QuestionDefinition_PromptText_PermanentResident {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_PermanentResident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where did you live before?.
        /// </summary>
        public static string QuestionDefinition_PromptText_PreviousAddress {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_PreviousAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where did you live before this?.
        /// </summary>
        public static string QuestionDefinition_PromptText_PreviousAddress1 {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_PreviousAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where did you live before this?.
        /// </summary>
        public static string QuestionDefinition_PromptText_PreviousAddress2 {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_PreviousAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you used your VA Entitlement before?.
        /// </summary>
        public static string QuestionDefinition_PromptText_PreviousUseOfVaEntitlement {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_PreviousUseOfVaEntitlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you had any property foreclosed on given title or deed in lieu thereof in the last 7 years?.
        /// </summary>
        public static string QuestionDefinition_PromptText_PropertyForeclosed {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_PropertyForeclosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the types of property you are interested in buying.
        /// </summary>
        public static string QuestionDefinition_PromptText_PropertyTypes {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_PropertyTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you receive child support?.
        /// </summary>
        public static string QuestionDefinition_PromptText_ReceiveChildSupport {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_ReceiveChildSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has the gift already been received?.
        /// </summary>
        public static string QuestionDefinition_PromptText_ReceivedGift {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_ReceivedGift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you taken on any recent debt?.
        /// </summary>
        public static string QuestionDefinition_PromptText_RecentDebt {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_RecentDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide additional recent debt details.
        /// </summary>
        public static string QuestionDefinition_PromptText_RecentDebtDetails {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_RecentDebtDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you sold any properties since you last filed your most recent tax return?.
        /// </summary>
        public static string QuestionDefinition_PromptText_RecentlySoldProperties {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_RecentlySoldProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like us to recommend you an agent?.
        /// </summary>
        public static string QuestionDefinition_PromptText_RecommendAgent {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_RecommendAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship of donor?.
        /// </summary>
        public static string QuestionDefinition_PromptText_RelationshipOfDonor {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_RelationshipOfDonor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you already requested the funds?.
        /// </summary>
        public static string QuestionDefinition_PromptText_RequestedTheFunds {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_RequestedTheFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have any retirement accounts and/or 401Ks?.
        /// </summary>
        public static string QuestionDefinition_PromptText_RetirementAccountsOr401Ks {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_RetirementAccountsOr401Ks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you Self Employed?.
        /// </summary>
        public static string QuestionDefinition_PromptText_SelfEmployed {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_SelfEmployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you sold a home for less than you owed, that resulted in a short sale transaction?.
        /// </summary>
        public static string QuestionDefinition_PromptText_ShortSale {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_ShortSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will your current home be sold before you purchase?.
        /// </summary>
        public static string QuestionDefinition_PromptText_SoldBeforePurchase {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_SoldBeforePurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the borrower&apos;s spouse&apos;s age.
        /// </summary>
        public static string QuestionDefinition_PromptText_SpouseAge {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_SpouseAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you presently delinquent or in default on any federal debt or any other loan, mortgage, financial obligation bond, or loan guarantee?.
        /// </summary>
        public static string QuestionDefinition_PromptText_StatusOfLoanDelinquency {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_StatusOfLoanDelinquency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What term are you thinking of applying for?.
        /// </summary>
        public static string QuestionDefinition_PromptText_TermsApplyingFor {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_TermsApplyingFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the timeframe for your purchase?.
        /// </summary>
        public static string QuestionDefinition_PromptText_TimeframeForPurchase {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_TimeframeForPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long have you been working overtime at current job?.
        /// </summary>
        public static string QuestionDefinition_PromptText_TimeOfWorkingOvertime {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_TimeOfWorkingOvertime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manner in which Title will be held.
        /// </summary>
        public static string QuestionDefinition_PromptText_TitleHolding {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_TitleHolding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What type of business is it?.
        /// </summary>
        public static string QuestionDefinition_PromptText_TypeOfBusiness {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_TypeOfBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What type of property was it?.
        /// </summary>
        public static string QuestionDefinition_PromptText_TypeOfOwnershipPropety {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_TypeOfOwnershipPropety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What type of property (you will enter properties one at a time).
        /// </summary>
        public static string QuestionDefinition_PromptText_TypeOfProperty {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_TypeOfProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you claim any unreimbursed employee expenses on your tax return?.
        /// </summary>
        public static string QuestionDefinition_PromptText_UnreimbursedEmployeeExpenses {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_UnreimbursedEmployeeExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you a US citizen?.
        /// </summary>
        public static string QuestionDefinition_PromptText_UsCitizen {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_UsCitizen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you claim any business use of home on your tax return?.
        /// </summary>
        public static string QuestionDefinition_PromptText_UseOfHomeForBusiness {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_UseOfHomeForBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you eligible for a Veteran Loan?.
        /// </summary>
        public static string QuestionDefinition_PromptText_VeteranLoan {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_VeteranLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When did you buy this home?.
        /// </summary>
        public static string QuestionDefinition_PromptText_WhenBuyHome {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_WhenBuyHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have a Work Visa?.
        /// </summary>
        public static string QuestionDefinition_PromptText_WorkVisa {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_WorkVisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of bankruptcy discharge?.
        /// </summary>
        public static string QuestionDefinition_PromptText_YearOfBankruptcyDischarge {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_YearOfBankruptcyDischarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many years of school have you completed, including college?.
        /// </summary>
        public static string QuestionDefinition_PromptText_YearsOfSchool {
            get {
                return ResourceManager.GetString("QuestionDefinition_PromptText_YearsOfSchool", resourceCulture);
            }
        }
    }
}
